# Generated by Django 6.1 on 2026-08-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('start_at', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=16)),
                ('recurrence_end', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('google', 'Google')], default='internal', max_length=16)),
                ('external_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['start_at'],
            },
        ),
    ]
