# Generated by Django 6.1 on 2026-08-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('timing_type', models.CharField(choices=[('exact', 'Exact time'), ('all_day', 'All day')], default='exact', max_length=16)),
                ('complete', models.BooleanField(default=False)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', max_length=16)),
                ('recurrence_end', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('internal', 'Internal'), ('google', 'Google')], default='internal', max_length=16)),
                ('external_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='uniq_calendar_event_source_external_id'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_gte_start_date')],
            },
        ),
    ]
