# Generated by Django 6.1 on 2026-08-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='duration',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='timing_type',
            field=models.CharField(choices=[('exact', 'Exact time'), ('anytime', 'Any time that day')], default='exact', max_length=16),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='recurrence_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='uniq_calendar_event_source_external_id'),
        ),
    ]
