# Generated by Django 6.1 on 2026-09-11 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEventException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_start_date', models.DateTimeField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('complete', models.BooleanField(blank=True, null=True)),
                ('timing_type', models.CharField(blank=True, choices=[('exact', 'Exact time'), ('all_day', 'All day')], max_length=16, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('external_local_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'calendar_event_exceptions',
                'ordering': ['original_start_date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='calendarevent',
            name='uniq_calendar_event_source_external_id',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='external_calendar_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='external_local_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_days_of_month',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_days_of_week',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_months_of_year',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_set_positions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='timezone',
            field=models.CharField(default='America/Los_Angeles', max_length=64),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='source',
            field=models.CharField(choices=[('internal', 'Internal'), ('google', 'Google'), ('apple', 'Apple')], default='internal', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_calendar_id', 'external_id'), name='uniq_calendar_event_external'),
        ),
        migrations.AddField(
            model_name='calendareventexception',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='calendar_events.calendarevent'),
        ),
        migrations.AddConstraint(
            model_name='calendareventexception',
            constraint=models.UniqueConstraint(fields=('event', 'original_start_date'), name='uniq_calendar_event_exception'),
        ),
    ]
