# Generated by Django 6.1 on 2026-08-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='google_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='google_channel_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='google_channel_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='account',
            name='google_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='google_sync_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
