# Generated by Django 6.1 on 2026-09-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_settings', '0002_seed_default_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsetting',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
