# Generated by Django 6.1 on 2026-08-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('store', models.CharField(choices=[('walmart', 'Walmart'), ('target', 'Target'), ('ralphs', 'Ralphs'), ('stater_bros', 'Stater Bros'), ('hmart', 'H-Mart'), ('99_ranch', '99 Ranch'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchased', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('grocery', 'Grocery'), ('supplies', 'Supplies'), ('household', 'Household'), ('personal_care', 'Personal Care'), ('electronics', 'Electronics'), ('other', 'Other')], default='other', max_length=20)),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
