# Generated by Django 6.1 on 2026-08-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.CharField(choices=[('walmart', 'Walmart'), ('target', 'Target'), ('ralphs', 'Ralphs'), ('stater_bros', 'Stater Bros'), ('hmart', 'H-Mart'), ('99_ranch', '99 Ranch'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('supplies', 'Supplies'), ('household', 'Household'), ('personal_care', 'Personal Care'), ('electronics', 'Electronics'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
