# Generated by Django 6.1 on 2026-09-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.CharField(choices=[('walmart', 'Walmart'), ('target', 'Target'), ('ralphs', 'Ralphs'), ('stater_bros', 'Stater Bros'), ('hmart', 'H-Mart'), ('99_ranch', '99 Ranch'), ('costco', 'Costco'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
